dist: xenial
cache: pip
language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8-dev
install:
- python setup.py -q install
script:
- python setup.py -q test
deploy:
  provider: pypi
  user: tonyyang
  password:
    secure: Ft7d5ATy3VLOLLz7fMjiXgo57tB/FhsSeACGejKJ390BLpRDunvrkeR8zorwCp39CgeYXC5QCje29tBNlanacciatoTBsMBNGifcGSklzE4RL4hQ5FeoA8ffJ2SSaOfiYN7FmgfAegi9OweL7pxn6KPpy/SE1wICg7m2Lk1JwfX/oD9z3WKiYJKm6EO9M9y1DJvyc/OD+LWdCNUg+Xpyq2jDZ4ciBsttHxHNwS6jtXGYQDNobuxjUsXxcb8rABbpEsREuLu3V770hQ6vAv7Fhe0Kn/4iZB17nBjB2GFxh3LDqqfuGxW07VUv+eC35pk3ZePPOzxrFzPaZk/7K+kjv0IA0okDKzEeBoIocmNl8LYSXZqzloR2sXsJeMOiddqqIiJ+ZfNBXZpzkptcH2bOS0FJoNfliELbp1syft00NndGVD0yUki6eUdyUxISV/Re7g/P2LWzAMsYF+KMc3uqnjpNlwtEeOczu8+fMZD2lKGLdp2joC68etVJ+hWvlfM39qHth7Yb0Lt4o2bGyEEDZyQNovkbHL4nmx3Z5+XdAsWpOK5Q8rq/xf0kMba1DdkN4jMu+kfkWKIHRPtj5LVMjDag2Tjfek9+YhpeajqzjqBW0gJ4jlnS+yZTP3VciDeAjBI8zN4YXK/8o73tVOf2D0iXumCXzUlE0NPpxfHB3lQ=
  distributions: sdist
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    repo: tonyyang-svail/setup.py
