dist: xenial
cache: pip
language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8-dev
install:
- python setup.py -q install
script:
- python setup.py -q test
deploy:
  provider: pypi
  user: tonyyang
  password:
    secure: QCaApvVFAMnMFk/hEAZ0ZiZ7GuPF3Ic+MX0VzgLaOw13QLS4EqgQfcKsTgCiamkv5GzvyMIoHTw7ntIGZKmOnGyu13Df3QKKeHD9536+4khPmQL30DQFOsV2rsrE31dE8uh4JtmOneaBc+DvqDhBWjv+Y5Ww/ahC81tbiBTJ/hfIT3lPjgW5PCrVS3ibg48G9pcjgXXmmFsAmstDYL4DMDVytg0hrIPc95LxkBQrUripsBcl7NhgQPd8pWjVSsEEwl0GjmCnrM43MxdOzitSy4nMc9rJM8R4FoYiFxIA6q/uHCFxHR79emjrcfYo4Q9vk8Pd8lbz9QMpxZurZdADZ0jDB33qTDbvwE60UXXEm9nyd6RV48rN9nBIbWlPi3bJ100/FeSJtEr7JqZdUSJ2gjn9h99HBFf/rRYfYuY7iM4AFhUmqlg3zJSHqDiaQOHkX5WikmuijerEkh9cGkBQvztbkj2udy6TvcdfuVNkDwWxVgy4zVrwnHfjrgjoAYV7CZr7vJ4In14LZGuGv4pmJ+wDHqjix5ng3HoJFkgkjKGtER1a13T/oyQyy5wliQSxdFPKsZY2NLOmvx3hQ+CI1vpAseo7z8MAs6zxHKccYEjI/92ccsFnHwGt7vzWrZQEjqMsMAOH740QHqPuz3SpPE66rhobMHTr/5OGmCFT8ag=
  distributions: sdist
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
